
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author smnsl
 */
public class GUI extends javax.swing.JFrame 
{

    /**
     * Creates new form GUI
     */
    CardLayout cardLayout;
    public GUI() 
    {
        initComponents();
        
        
        cardLayout = (CardLayout) (jp_CardHandler.getLayout());
        
        /*
        jp_MainMenu.setVisible(false);
        jp_MyProfilePanel.setVisible(false);
        jp_ModifyPanel.setVisible(false);
        jp_LGToSUPanel.setVisible(false);
        */
        
        
        Player p1 = new Player("Dumy1", "Test1");
        Player p2 = new Player("Dumy2", "Test2");
        logger.addPlayer(p1);
        logger.addPlayer(p2);
        p1.setPlayerScore(123);
        p2.setPlayerScore(123);
        GhostGame[] gr1 = p1.getGameReports();
        for (int i = 0; i < gr1.length; i++)
        {
            gr1[i] = new GhostGame(3, p2.getUsername(), true);
            gr1[i].setDescription("Este es una prueba! Le has ganado a " + p2.getUsername());
        }
        
        
        /*
        ImageIcon board = new ImageIcon();
        System.out.println(board.getIconHeight() + " y " + board.getIconWidth());
        jl_board.setIcon(board);
        */
        
        
        //jp_CardHandler.setVisible(true);
        cardLayout.show(jp_CardHandler, "LoginCard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_CardHandler = new javax.swing.JPanel();
        jp_SUBackground = new javax.swing.JPanel();
        jp_SUIconBackground = new javax.swing.JPanel();
        jl_SUGhostIcon = new javax.swing.JLabel();
        jp_SDataBackground = new javax.swing.JPanel();
        jb_SUSignUpButton = new javax.swing.JButton();
        jl_SUNameLabel = new javax.swing.JLabel();
        jl_SULoginMenuTitle = new javax.swing.JLabel();
        jtf_SUNameField = new javax.swing.JTextField();
        jl_SUPasswordLabel = new javax.swing.JLabel();
        jtf_SUPasswordField = new javax.swing.JTextField();
        jp_ToLogPanel = new javax.swing.JPanel();
        jl_SUHaveAccount = new javax.swing.JLabel();
        jb_SUGoToLoginButton = new javax.swing.JButton();
        jp_LGBackground = new javax.swing.JPanel();
        jp_LIconBackground = new javax.swing.JPanel();
        jl_GhostIcon1 = new javax.swing.JLabel();
        jp_LGDataBackground = new javax.swing.JPanel();
        jb_LGLoginButton = new javax.swing.JButton();
        jl_LGNameLabel = new javax.swing.JLabel();
        jl_LGLoginMenuTitle = new javax.swing.JLabel();
        jtf_LGNameField = new javax.swing.JTextField();
        jl_LGPasswordLabel = new javax.swing.JLabel();
        jtf_LGPasswordField = new javax.swing.JTextField();
        jp_LGToSUPanel = new javax.swing.JPanel();
        jl_LGCreateAccount = new javax.swing.JLabel();
        jb_LGGoToSUButton = new javax.swing.JButton();
        jp_MainMenu = new javax.swing.JPanel();
        jp_MenuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jb_PlayButton = new javax.swing.JButton();
        jb_SettingsButton = new javax.swing.JButton();
        jb_ReportsButton = new javax.swing.JButton();
        jb_MyProfileButton = new javax.swing.JButton();
        jb_ExitButton = new javax.swing.JButton();
        jb_CloseSessionButton = new javax.swing.JButton();
        jp_SettingsPanel = new javax.swing.JPanel();
        jp_SettingsMenuPanel = new javax.swing.JPanel();
        jl_SettingTitle = new javax.swing.JLabel();
        jl_DifficultyLabel = new javax.swing.JLabel();
        jl_GamemodeLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jcb_DifficultyBox = new javax.swing.JComboBox<>();
        jcb_GamemodebBox = new javax.swing.JComboBox<>();
        jb_SettingBackToMenuButton = new javax.swing.JButton();
        jp_ReportsPanel = new javax.swing.JPanel();
        jp_ReportsMenuBG = new javax.swing.JPanel();
        jl_ReportsTitle = new javax.swing.JLabel();
        jb_RankingButton = new javax.swing.JButton();
        jb_10GamesButton = new javax.swing.JButton();
        jb_ReportsToMenuButton = new javax.swing.JButton();
        jp_10GamesPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_10GamesTable = new javax.swing.JTable();
        jp_MyProfilePanel = new javax.swing.JPanel();
        jp_ProfileSettings = new javax.swing.JPanel();
        jl_MyProfileTitle = new javax.swing.JLabel();
        jb_BackToMainMenuButton = new javax.swing.JButton();
        jb_ModifyButton = new javax.swing.JButton();
        jb_EraseAccountButton = new javax.swing.JButton();
        jp_ModifyPanel = new javax.swing.JPanel();
        jl_ChangePassTitle = new javax.swing.JLabel();
        jl_ChangeNameTitle = new javax.swing.JLabel();
        jtf_PassChangerField = new javax.swing.JTextField();
        jtf_NameChangerField = new javax.swing.JTextField();
        jb_UpdateButton = new javax.swing.JButton();
        jp_ProfileDataPanel = new javax.swing.JPanel();
        jl_UsernameTitle = new javax.swing.JLabel();
        jl_UsernameGoesHere = new javax.swing.JLabel();
        jl_PasswordTitle = new javax.swing.JLabel();
        jl_PasswordGoesHere = new javax.swing.JLabel();
        jl_ScoreTitle = new javax.swing.JLabel();
        jl_ScoreGoesHere = new javax.swing.JLabel();
        jsp_GamePanel = new javax.swing.JSplitPane();
        jp_BoardSidebar = new javax.swing.JPanel();
        JL_GhostsLabel = new javax.swing.JLabel();
        jl_EnemyLabel = new javax.swing.JLabel();
        jl_EnemyNameGoesHere = new javax.swing.JLabel();
        jl_HisGoodGhosts = new javax.swing.JLabel();
        jl_HisGoodNumber = new javax.swing.JLabel();
        jl_HisBadGhosts = new javax.swing.JLabel();
        jl_HisBadNumber = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jl_You = new javax.swing.JLabel();
        jl_LoggedNameGoesHere = new javax.swing.JLabel();
        JL_YourGoodGhosts = new javax.swing.JLabel();
        jl_YourBadGhosts = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jl_LoggedGoodNumber = new javax.swing.JLabel();
        jl_LoggedBadNumber = new javax.swing.JLabel();
        jb_SurrenderButton = new javax.swing.JButton();
        jp_BoardPanel = new javax.swing.JPanel();
        jl_board = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ghosts");
        setMinimumSize(new java.awt.Dimension(880, 680));
        setResizable(false);

        jp_CardHandler.setLayout(new java.awt.CardLayout());

        jp_SUBackground.setBackground(new java.awt.Color(51, 51, 51));
        jp_SUBackground.setMaximumSize(new java.awt.Dimension(1980, 1080));
        jp_SUBackground.setMinimumSize(new java.awt.Dimension(880, 680));

        jp_SUIconBackground.setBackground(new java.awt.Color(0, 153, 153));
        jp_SUIconBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_SUGhostIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghost.png1.png"))); // NOI18N
        jl_SUGhostIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jp_SUIconBackground.add(jl_SUGhostIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-550, -60, -1, -1));

        jp_SDataBackground.setBackground(new java.awt.Color(204, 204, 204));
        jp_SDataBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_SUSignUpButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jb_SUSignUpButton.setText("Sign Up");
        jb_SUSignUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_SUSignUpButtonMouseClicked(evt);
            }
        });
        jp_SDataBackground.add(jb_SUSignUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 110, 50));

        jl_SUNameLabel.setBackground(new java.awt.Color(51, 51, 51));
        jl_SUNameLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_SUNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        jl_SUNameLabel.setText("Name");
        jp_SDataBackground.add(jl_SUNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jl_SULoginMenuTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jl_SULoginMenuTitle.setForeground(new java.awt.Color(0, 0, 0));
        jl_SULoginMenuTitle.setText("SIGN UP");
        jp_SDataBackground.add(jl_SULoginMenuTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jtf_SUNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_SUNameFieldActionPerformed(evt);
            }
        });
        jp_SDataBackground.add(jtf_SUNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 430, 50));

        jl_SUPasswordLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_SUPasswordLabel.setForeground(new java.awt.Color(51, 51, 51));
        jl_SUPasswordLabel.setText("Password");
        jp_SDataBackground.add(jl_SUPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));
        jp_SDataBackground.add(jtf_SUPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 430, 50));

        jp_ToLogPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_SUHaveAccount.setText("Already have an account?");
        jp_ToLogPanel.add(jl_SUHaveAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jb_SUGoToLoginButton.setBackground(new java.awt.Color(204, 204, 204));
        jb_SUGoToLoginButton.setForeground(new java.awt.Color(51, 51, 51));
        jb_SUGoToLoginButton.setText("Log In");
        jb_SUGoToLoginButton.setToolTipText("");
        jb_SUGoToLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_SUGoToLoginButtonMouseClicked(evt);
            }
        });
        jp_ToLogPanel.add(jb_SUGoToLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jp_SDataBackground.add(jp_ToLogPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, 250, 40));

        javax.swing.GroupLayout jp_SUBackgroundLayout = new javax.swing.GroupLayout(jp_SUBackground);
        jp_SUBackground.setLayout(jp_SUBackgroundLayout);
        jp_SUBackgroundLayout.setHorizontalGroup(
            jp_SUBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_SUBackgroundLayout.createSequentialGroup()
                .addComponent(jp_SUIconBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jp_SDataBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jp_SUBackgroundLayout.setVerticalGroup(
            jp_SUBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_SUIconBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jp_SDataBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jp_CardHandler.add(jp_SUBackground, "SignUpCard");

        jp_LGBackground.setBackground(new java.awt.Color(51, 51, 51));
        jp_LGBackground.setMaximumSize(new java.awt.Dimension(1960, 1080));
        jp_LGBackground.setMinimumSize(new java.awt.Dimension(880, 685));
        jp_LGBackground.setPreferredSize(new java.awt.Dimension(880, 690));
        jp_LGBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_LIconBackground.setBackground(new java.awt.Color(0, 153, 153));
        jp_LIconBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_GhostIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghost.png1.png"))); // NOI18N
        jl_GhostIcon1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jp_LIconBackground.add(jl_GhostIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-550, -60, -1, -1));

        jp_LGBackground.add(jp_LIconBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 680));

        jp_LGDataBackground.setBackground(new java.awt.Color(204, 204, 204));
        jp_LGDataBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_LGLoginButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jb_LGLoginButton.setText("Log In");
        jb_LGLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_LGLoginButtonMouseClicked(evt);
            }
        });
        jp_LGDataBackground.add(jb_LGLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 110, 50));

        jl_LGNameLabel.setBackground(new java.awt.Color(51, 51, 51));
        jl_LGNameLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_LGNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        jl_LGNameLabel.setText("Name");
        jp_LGDataBackground.add(jl_LGNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jl_LGLoginMenuTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jl_LGLoginMenuTitle.setForeground(new java.awt.Color(0, 0, 0));
        jl_LGLoginMenuTitle.setText("LOGIN");
        jp_LGDataBackground.add(jl_LGLoginMenuTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));
        jp_LGDataBackground.add(jtf_LGNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 430, 50));

        jl_LGPasswordLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_LGPasswordLabel.setForeground(new java.awt.Color(51, 51, 51));
        jl_LGPasswordLabel.setText("Password");
        jp_LGDataBackground.add(jl_LGPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));
        jp_LGDataBackground.add(jtf_LGPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 430, 50));

        jp_LGToSUPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_LGCreateAccount.setText("Don't have an account?");
        jp_LGToSUPanel.add(jl_LGCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jb_LGGoToSUButton.setBackground(new java.awt.Color(204, 204, 204));
        jb_LGGoToSUButton.setForeground(new java.awt.Color(51, 51, 51));
        jb_LGGoToSUButton.setText("Sign Up");
        jb_LGGoToSUButton.setToolTipText("");
        jb_LGGoToSUButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_LGGoToSUButtonMouseClicked(evt);
            }
        });
        jp_LGToSUPanel.add(jb_LGGoToSUButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jp_LGDataBackground.add(jp_LGToSUPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, 240, 40));

        jp_LGBackground.add(jp_LGDataBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 550, 680));

        jp_CardHandler.add(jp_LGBackground, "LoginCard");

        jp_MainMenu.setMaximumSize(new java.awt.Dimension(1970, 1080));
        jp_MainMenu.setMinimumSize(new java.awt.Dimension(880, 680));
        jp_MainMenu.setPreferredSize(new java.awt.Dimension(880, 680));
        jp_MainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_MenuPanel.setBackground(new java.awt.Color(102, 102, 102));
        jp_MenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("MAIN MENU");
        jp_MenuPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jb_PlayButton.setText("Play");
        jb_PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_PlayButtonActionPerformed(evt);
            }
        });
        jp_MenuPanel.add(jb_PlayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 120, -1));

        jb_SettingsButton.setText("Settings");
        jb_SettingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_SettingsButtonMouseClicked(evt);
            }
        });
        jp_MenuPanel.add(jb_SettingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 120, -1));

        jb_ReportsButton.setText("Reports");
        jb_ReportsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ReportsButtonMouseClicked(evt);
            }
        });
        jp_MenuPanel.add(jb_ReportsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 120, -1));

        jb_MyProfileButton.setText("My Profile");
        jb_MyProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_MyProfileButtonMouseClicked(evt);
            }
        });
        jp_MenuPanel.add(jb_MyProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 120, -1));

        jb_ExitButton.setText("Exit");
        jb_ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ExitButtonMouseClicked(evt);
            }
        });
        jb_ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ExitButtonActionPerformed(evt);
            }
        });
        jp_MenuPanel.add(jb_ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 120, -1));

        jb_CloseSessionButton.setText("Close Session");
        jb_CloseSessionButton.setToolTipText("");
        jb_CloseSessionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CloseSessionButtonMouseClicked(evt);
            }
        });
        jp_MenuPanel.add(jb_CloseSessionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 120, -1));

        jp_MainMenu.add(jp_MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 420, 680));

        jp_CardHandler.add(jp_MainMenu, "MainMenuCard");

        jp_SettingsPanel.setBackground(new java.awt.Color(102, 102, 102));

        jl_SettingTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_SettingTitle.setText("SETTINGS");

        jl_DifficultyLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_DifficultyLabel.setText("Difficulty");

        jl_GamemodeLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_GamemodeLabel.setText("Gamemode");

        jcb_DifficultyBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NORMAL", "EXPERT", "GENIUS" }));

        jcb_GamemodebBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RANDOM", "MANUAL" }));

        jb_SettingBackToMenuButton.setText("Back to menu");
        jb_SettingBackToMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_SettingBackToMenuButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_SettingsMenuPanelLayout = new javax.swing.GroupLayout(jp_SettingsMenuPanel);
        jp_SettingsMenuPanel.setLayout(jp_SettingsMenuPanelLayout);
        jp_SettingsMenuPanelLayout.setHorizontalGroup(
            jp_SettingsMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_SettingsMenuPanelLayout.createSequentialGroup()
                .addGroup(jp_SettingsMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_SettingsMenuPanelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jl_SettingTitle))
                    .addGroup(jp_SettingsMenuPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jp_SettingsMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_GamemodeLabel)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_DifficultyLabel))))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_SettingsMenuPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jcb_DifficultyBox, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jp_SettingsMenuPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jcb_GamemodebBox, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jp_SettingsMenuPanelLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jb_SettingBackToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_SettingsMenuPanelLayout.setVerticalGroup(
            jp_SettingsMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_SettingsMenuPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jl_SettingTitle)
                .addGap(47, 47, 47)
                .addComponent(jl_DifficultyLabel)
                .addGap(18, 18, 18)
                .addComponent(jcb_DifficultyBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jl_GamemodeLabel)
                .addGap(18, 18, 18)
                .addComponent(jcb_GamemodebBox, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jb_SettingBackToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout jp_SettingsPanelLayout = new javax.swing.GroupLayout(jp_SettingsPanel);
        jp_SettingsPanel.setLayout(jp_SettingsPanelLayout);
        jp_SettingsPanelLayout.setHorizontalGroup(
            jp_SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_SettingsPanelLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jp_SettingsMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jp_SettingsPanelLayout.setVerticalGroup(
            jp_SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_SettingsMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jp_CardHandler.add(jp_SettingsPanel, "SettingsCard");

        jp_ReportsPanel.setMaximumSize(new java.awt.Dimension(1970, 1080));
        jp_ReportsPanel.setMinimumSize(new java.awt.Dimension(880, 680));
        jp_ReportsPanel.setPreferredSize(new java.awt.Dimension(880, 685));
        jp_ReportsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_ReportsMenuBG.setBackground(new java.awt.Color(153, 153, 153));
        jp_ReportsMenuBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_ReportsTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jl_ReportsTitle.setForeground(new java.awt.Color(51, 51, 51));
        jl_ReportsTitle.setText("MENU");
        jp_ReportsMenuBG.add(jl_ReportsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jb_RankingButton.setText("Leaderboards");
        jb_RankingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_RankingButtonMouseClicked(evt);
            }
        });
        jp_ReportsMenuBG.add(jb_RankingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 120, 50));

        jb_10GamesButton.setText("Last 10 games");
        jb_10GamesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_10GamesButtonMouseClicked(evt);
            }
        });
        jp_ReportsMenuBG.add(jb_10GamesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 120, 50));

        jb_ReportsToMenuButton.setText("Back to menu");
        jb_ReportsToMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ReportsToMenuButtonMouseClicked(evt);
            }
        });
        jb_ReportsToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ReportsToMenuButtonActionPerformed(evt);
            }
        });
        jp_ReportsMenuBG.add(jb_ReportsToMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 120, 50));

        jp_ReportsPanel.add(jp_ReportsMenuBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 220, 690));

        jp_10GamesPanel.setBackground(new java.awt.Color(102, 102, 102));
        jp_10GamesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jt_10GamesTable.setBackground(new java.awt.Color(153, 153, 153));
        jt_10GamesTable.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jt_10GamesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Game description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_10GamesTable);

        jp_10GamesPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 32, 500, 580));

        jp_ReportsPanel.add(jp_10GamesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 580, 650));

        jp_CardHandler.add(jp_ReportsPanel, "ReportsCard");

        jp_MyProfilePanel.setBackground(new java.awt.Color(204, 204, 204));
        jp_MyProfilePanel.setMaximumSize(new java.awt.Dimension(1970, 1080));
        jp_MyProfilePanel.setMinimumSize(new java.awt.Dimension(880, 680));
        jp_MyProfilePanel.setPreferredSize(new java.awt.Dimension(880, 680));
        jp_MyProfilePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_ProfileSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_MyProfileTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jl_MyProfileTitle.setText("My Profile");
        jp_ProfileSettings.add(jl_MyProfileTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jb_BackToMainMenuButton.setText("Back to menu");
        jb_BackToMainMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_BackToMainMenuButtonMouseClicked(evt);
            }
        });
        jp_ProfileSettings.add(jb_BackToMainMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 130, 50));

        jb_ModifyButton.setText("Modify Profile");
        jb_ModifyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ModifyButtonMouseClicked(evt);
            }
        });
        jb_ModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ModifyButtonActionPerformed(evt);
            }
        });
        jp_ProfileSettings.add(jb_ModifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 130, 50));

        jb_EraseAccountButton.setText("Erase Account");
        jb_EraseAccountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_EraseAccountButtonMouseClicked(evt);
            }
        });
        jp_ProfileSettings.add(jb_EraseAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 130, 50));

        jp_MyProfilePanel.add(jp_ProfileSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 680));

        jp_ModifyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_ChangePassTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_ChangePassTitle.setText("Change your password");
        jp_ModifyPanel.add(jl_ChangePassTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jl_ChangeNameTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_ChangeNameTitle.setText("Change your password");
        jp_ModifyPanel.add(jl_ChangeNameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));
        jp_ModifyPanel.add(jtf_PassChangerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 290, 60));
        jp_ModifyPanel.add(jtf_NameChangerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 290, 60));

        jb_UpdateButton.setText("Update");
        jb_UpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_UpdateButtonMouseClicked(evt);
            }
        });
        jb_UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_UpdateButtonActionPerformed(evt);
            }
        });
        jp_ModifyPanel.add(jb_UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 110, 50));

        jp_MyProfilePanel.add(jp_ModifyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 440, 500));

        jp_ProfileDataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_UsernameTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jl_UsernameTitle.setText("Player Username");
        jp_ProfileDataPanel.add(jl_UsernameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 370, 80));

        jl_UsernameGoesHere.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jp_ProfileDataPanel.add(jl_UsernameGoesHere, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 300, 70));

        jl_PasswordTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jl_PasswordTitle.setText("Password");
        jp_ProfileDataPanel.add(jl_PasswordTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 370, 80));

        jl_PasswordGoesHere.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jp_ProfileDataPanel.add(jl_PasswordGoesHere, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 300, 70));

        jl_ScoreTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jl_ScoreTitle.setText("Total Player Score");
        jp_ProfileDataPanel.add(jl_ScoreTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 370, 80));

        jl_ScoreGoesHere.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jp_ProfileDataPanel.add(jl_ScoreGoesHere, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 300, 70));

        jp_MyProfilePanel.add(jp_ProfileDataPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 440, 500));

        jp_CardHandler.add(jp_MyProfilePanel, "ProfileCard");

        jsp_GamePanel.setDividerLocation(200);
        jsp_GamePanel.setMaximumSize(new java.awt.Dimension(1970, 1080));
        jsp_GamePanel.setMinimumSize(new java.awt.Dimension(900, 700));
        jsp_GamePanel.setPreferredSize(new java.awt.Dimension(900, 700));
        jsp_GamePanel.setRequestFocusEnabled(false);

        jp_BoardSidebar.setBackground(new java.awt.Color(153, 153, 153));

        JL_GhostsLabel.setBackground(new java.awt.Color(51, 51, 51));
        JL_GhostsLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        JL_GhostsLabel.setForeground(new java.awt.Color(51, 51, 51));
        JL_GhostsLabel.setText("GHOSTS");

        jl_EnemyLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jl_EnemyLabel.setForeground(new java.awt.Color(51, 51, 51));
        jl_EnemyLabel.setText("Enemy Player:");

        jl_EnemyNameGoesHere.setForeground(new java.awt.Color(51, 51, 51));

        jl_HisGoodGhosts.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jl_HisGoodGhosts.setForeground(new java.awt.Color(51, 51, 51));
        jl_HisGoodGhosts.setText("His good ghosts:");

        jl_HisGoodNumber.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jl_HisGoodNumber.setForeground(new java.awt.Color(51, 51, 51));

        jl_HisBadGhosts.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jl_HisBadGhosts.setForeground(new java.awt.Color(51, 51, 51));
        jl_HisBadGhosts.setText("His bad ghosts:");

        jl_HisBadNumber.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jl_HisBadNumber.setForeground(new java.awt.Color(51, 51, 51));

        jl_You.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jl_You.setForeground(new java.awt.Color(51, 51, 51));
        jl_You.setText("You:");

        jl_LoggedNameGoesHere.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jl_LoggedNameGoesHere.setForeground(new java.awt.Color(51, 51, 51));

        JL_YourGoodGhosts.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        JL_YourGoodGhosts.setForeground(new java.awt.Color(51, 51, 51));
        JL_YourGoodGhosts.setText("Your good ghosts:");

        jl_YourBadGhosts.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jl_YourBadGhosts.setForeground(new java.awt.Color(51, 51, 51));
        jl_YourBadGhosts.setText("Your bad ghosts:");

        jl_LoggedGoodNumber.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jl_LoggedGoodNumber.setForeground(new java.awt.Color(51, 51, 51));

        jl_LoggedBadNumber.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jl_LoggedBadNumber.setForeground(new java.awt.Color(51, 51, 51));

        jb_SurrenderButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jb_SurrenderButton.setText("SURRENDER");

        javax.swing.GroupLayout jp_BoardSidebarLayout = new javax.swing.GroupLayout(jp_BoardSidebar);
        jp_BoardSidebar.setLayout(jp_BoardSidebarLayout);
        jp_BoardSidebarLayout.setHorizontalGroup(
            jp_BoardSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_BoardSidebarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jl_EnemyNameGoesHere, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jp_BoardSidebarLayout.createSequentialGroup()
                .addGroup(jp_BoardSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_BoardSidebarLayout.createSequentialGroup()
                        .addGroup(jp_BoardSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_BoardSidebarLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(JL_GhostsLabel))
                            .addGroup(jp_BoardSidebarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jl_EnemyLabel)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jp_BoardSidebarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jp_BoardSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_BoardSidebarLayout.createSequentialGroup()
                                .addComponent(jl_HisGoodGhosts)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jl_HisGoodNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator3))))
                .addContainerGap())
            .addGroup(jp_BoardSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_BoardSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_BoardSidebarLayout.createSequentialGroup()
                        .addGroup(jp_BoardSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4)
                            .addGroup(jp_BoardSidebarLayout.createSequentialGroup()
                                .addGroup(jp_BoardSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_BoardSidebarLayout.createSequentialGroup()
                                        .addComponent(jl_HisBadGhosts)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jl_HisBadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jl_You)
                                    .addComponent(JL_YourGoodGhosts)
                                    .addGroup(jp_BoardSidebarLayout.createSequentialGroup()
                                        .addComponent(jl_YourBadGhosts)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jl_LoggedBadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_BoardSidebarLayout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addGroup(jp_BoardSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_LoggedGoodNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_LoggedNameGoesHere, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))))
            .addGroup(jp_BoardSidebarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jb_SurrenderButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jp_BoardSidebarLayout.setVerticalGroup(
            jp_BoardSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_BoardSidebarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(JL_GhostsLabel)
                .addGap(27, 27, 27)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jp_BoardSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_BoardSidebarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_EnemyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_EnemyNameGoesHere, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_HisGoodGhosts))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_BoardSidebarLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jl_HisGoodNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jp_BoardSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_HisBadGhosts)
                    .addComponent(jl_HisBadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jb_SurrenderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jp_BoardSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_BoardSidebarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_You)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_LoggedNameGoesHere, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_BoardSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JL_YourGoodGhosts)
                            .addComponent(jl_LoggedGoodNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jl_YourBadGhosts))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_BoardSidebarLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jl_LoggedBadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );

        jsp_GamePanel.setLeftComponent(jp_BoardSidebar);

        jp_BoardPanel.setBackground(new java.awt.Color(102, 102, 102));
        jp_BoardPanel.setForeground(new java.awt.Color(51, 51, 51));

        jl_board.setIcon(new javax.swing.ImageIcon("C:\\Users\\smnsl\\OneDrive\\Documentos\\NetBeansProjects\\Programacion2_Ghosts\\Images\\6x6.png")); // NOI18N
        jp_BoardPanel.add(jl_board);

        jsp_GamePanel.setRightComponent(jp_BoardPanel);

        jp_CardHandler.add(jsp_GamePanel, "GameCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_CardHandler, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_CardHandler, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("MainFrame");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_LGLoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_LGLoginButtonMouseClicked
        // TODO add your handling code here:
        String nombre = jtf_LGNameField.getText();
        String contra = jtf_LGPasswordField.getText();

        if (nombre.isBlank() || contra.isBlank()) 
        {
            JOptionPane.showMessageDialog(this, "Please do not leave empty spaces.");
        } else 
        {
            if (logger.search(nombre) == null) 
            {
                JOptionPane.showMessageDialog(this, "This user does not exist.");
            } else 
            {
                Player p = logger.search(nombre);
                p.setLoggedIn(logger.login(nombre, contra));
                
                if (p.isLoggedIn())
                {
                    
                    JOptionPane.showMessageDialog(this, "Starting...");
                    
                    /*
                    jp_LGBackground.setVisible(false);
                    jp_MainMenu.setVisible(true);
                    */
                    
                    cardLayout.show(jp_CardHandler, "MainMenuCard");

                }else
                {
                    JOptionPane.showMessageDialog(this, "Wrong password.");
                }
                
                logger.listPlayers();
            }
        }
    }//GEN-LAST:event_jb_LGLoginButtonMouseClicked

    private void jtf_SUNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_SUNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_SUNameFieldActionPerformed

    private void jb_SUSignUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_SUSignUpButtonMouseClicked
        // TODO add your handling code here:
        String nombre = jtf_SUNameField.getText();
        String contra = jtf_SUPasswordField.getText();
        
        if (nombre.isBlank() || contra.isBlank() )
        {
            JOptionPane.showMessageDialog(this, "Please do not leave empty spaces");
        } else
        {
            if ( logger.search(nombre) != null)
            {
                JOptionPane.showMessageDialog(this, "This user already exists.");
            } else
            {
                Player p = new Player(nombre, contra);
                logger.addPlayer(p);
                p.setLoggedIn(logger.login(nombre, contra));
                JOptionPane.showMessageDialog(this, "User added successfully.");

                /*
                jp_SUBackground.setVisible(false);
                jp_MainMenu.setVisible(true);
                */
                
                cardLayout.show(jp_CardHandler, "MainMenuCard");

                logger.listPlayers();
            }
        }
    }//GEN-LAST:event_jb_SUSignUpButtonMouseClicked

    private void jb_LGGoToSUButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_LGGoToSUButtonMouseClicked
        // TODO add your handling code here:
        /*
        jp_LGBackground.setVisible(false);
        jp_SUBackground.setVisible(true);
        */
        cardLayout.show(jp_CardHandler, "SignUpCard");
    }//GEN-LAST:event_jb_LGGoToSUButtonMouseClicked

    private void jb_SUGoToLoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_SUGoToLoginButtonMouseClicked
        // TODO add your handling code here:
        /*
        jp_LGBackground.setVisible(true);
        jp_SUBackground.setVisible(false);
        jp_LGToSUPanel.setVisible(true);
        */
        cardLayout.show(jp_CardHandler, "LoginCard");

    }//GEN-LAST:event_jb_SUGoToLoginButtonMouseClicked

    private void jb_PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_PlayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_PlayButtonActionPerformed

    private void jb_ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ExitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_ExitButtonActionPerformed

    private void jb_ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ExitButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jb_ExitButtonMouseClicked

    private void jb_CloseSessionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CloseSessionButtonMouseClicked
        // TODO add your handling code here:
        /*
        jp_LGBackground.setVisible(true);
        jp_MainMenu.setVisible(false);
        */
        
        cardLayout.show(jp_CardHandler, "SignUpCard");

        
        Player p = logger.getLoggedInPlayer();
        p.setLoggedIn(false);
        logger.listPlayers();
        
    }//GEN-LAST:event_jb_CloseSessionButtonMouseClicked

    private void jb_ModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ModifyButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jb_ModifyButtonActionPerformed

    private void jb_MyProfileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_MyProfileButtonMouseClicked
        // TODO add your handling code here:
        /*
        jp_MainMenu.setVisible(false);
        jp_MyProfilePanel.setVisible(true);
        */
        
        cardLayout.show(jp_CardHandler, "ProfileCard");
        jp_ModifyPanel.setVisible(false);
        
        Player p = logger.getLoggedInPlayer();

        jl_UsernameGoesHere.setText(p.getUsername());
        jl_PasswordGoesHere.setText(p.getPassword());
        jl_ScoreGoesHere.setText(p.getPlayerScore() + " points");
        
    }//GEN-LAST:event_jb_MyProfileButtonMouseClicked

    private void jb_ModifyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ModifyButtonMouseClicked
        // TODO add your handling code here:
        Player p = logger.getLoggedInPlayer();
        
        jtf_NameChangerField.setText(p.getUsername());
        jtf_PassChangerField.setText(p.getPassword());
        
        jp_ProfileDataPanel.setVisible(false);
        jp_ModifyPanel.setVisible(true);
        
    }//GEN-LAST:event_jb_ModifyButtonMouseClicked

    private void jb_UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_UpdateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_UpdateButtonActionPerformed

    private void jb_UpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_UpdateButtonMouseClicked
        // TODO add your handling code here:
        Player p = logger.getLoggedInPlayer();
        
        String newName = jtf_NameChangerField.getText();
        String newPass = jtf_PassChangerField.getText();
        
        if (newName.isBlank() || newPass.isBlank())
        {
            JOptionPane.showMessageDialog(this, "Please do not leave empty spaces.");
        } else
        {
            p.setUsername(newName);
            p.setPassword(newPass);
            JOptionPane.showMessageDialog(this, "Profile data updated successfully");
            logger.listPlayers();
            jp_ModifyPanel.setVisible(false);
            jp_ProfileDataPanel.setVisible(true);
            
            
            
            jl_UsernameGoesHere.setText(p.getUsername());
            jl_PasswordGoesHere.setText(p.getPassword());
            jl_ScoreGoesHere.setText(p.getPlayerScore() + " points");
        }
        

        
    }//GEN-LAST:event_jb_UpdateButtonMouseClicked

    private void jb_BackToMainMenuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_BackToMainMenuButtonMouseClicked
        // TODO add your handling code here:
        jp_MyProfilePanel.setVisible(false);
        jp_MainMenu.setVisible(true);
    }//GEN-LAST:event_jb_BackToMainMenuButtonMouseClicked

    private void jb_EraseAccountButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_EraseAccountButtonMouseClicked
        // TODO add your handling code here:
        int option;
        
        if (JOptionPane.showConfirmDialog(this, "Are you sure you want to erase your profile?", "Erase Account", JOptionPane.YES_NO_OPTION) == 0)
        {
            Player p = logger.getLoggedInPlayer();

            logger.getPlayers().remove(p);

            jp_LGBackground.setVisible(true);
            //jp_MainMenu.setVisible(false);
            jp_MyProfilePanel.setVisible(false);
            logger.listPlayers();
        }
        
        
        
    }//GEN-LAST:event_jb_EraseAccountButtonMouseClicked

    private void jb_10GamesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_10GamesButtonMouseClicked
        // TODO add your handling code here:
        jp_ReportsPanel.setVisible(true);
        jp_10GamesPanel.setVisible(true);
        Player p = logger.getLoggedInPlayer();
        
         //jt_10GamesTable.setModel(new DefaultTableModel(null, new String[]{"Game Description"}));
        
         
        Object rowData[] = new Object[1];
        DefaultTableModel tblm = (DefaultTableModel) jt_10GamesTable.getModel();

        if (!alreadyInTable) 
        {
            for (int i = 0; i < p.getGameReports().length; i++)
            {
                rowData[0] = p.getGameReports()[i].getDescription();

                tblm.addRow(rowData);
                alreadyInTable = true;
            }
        }
            
        
    }//GEN-LAST:event_jb_10GamesButtonMouseClicked

    private void jb_ReportsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ReportsButtonMouseClicked
        // TODO add your handling code here:
        /*
        jp_MainMenu.setVisible(false);
        jp_ReportsPanel.setVisible(true);
        jp_10GamesPanel.setVisible(false);
        */
        
        cardLayout.show(jp_CardHandler, "ReportsCard");

    }//GEN-LAST:event_jb_ReportsButtonMouseClicked

    private void jb_RankingButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_RankingButtonMouseClicked
        // TODO add your handling code here:
        jp_10GamesPanel.setVisible(false);
        jp_ReportsPanel.setVisible(true);
        
        
        
        
        
    }//GEN-LAST:event_jb_RankingButtonMouseClicked

    private void jb_ReportsToMenuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ReportsToMenuButtonMouseClicked
        // TODO add your handling code here:
        jp_MainMenu.setVisible(true);
        jp_ReportsPanel.setVisible(false);
        //jp_ReportsMenuBG.setVisible(false);
        //jp_10GamesPanel.setVisible(false);
        
    }//GEN-LAST:event_jb_ReportsToMenuButtonMouseClicked

    private void jb_ReportsToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ReportsToMenuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_ReportsToMenuButtonActionPerformed

    private void jb_SettingBackToMenuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_SettingBackToMenuButtonMouseClicked
        // TODO add your handling code here:
        cardLayout.show(jp_CardHandler, "MainMenuCard");
        
        
        
        
        
        
        

    }//GEN-LAST:event_jb_SettingBackToMenuButtonMouseClicked

    private void jb_SettingsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_SettingsButtonMouseClicked
        // TODO add your handling code here:
        cardLayout.show(jp_CardHandler, "SettingsCard");
    }//GEN-LAST:event_jb_SettingsButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_GhostsLabel;
    private javax.swing.JLabel JL_YourGoodGhosts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton jb_10GamesButton;
    private javax.swing.JButton jb_BackToMainMenuButton;
    private javax.swing.JButton jb_CloseSessionButton;
    private javax.swing.JButton jb_EraseAccountButton;
    private javax.swing.JButton jb_ExitButton;
    private javax.swing.JButton jb_LGGoToSUButton;
    private javax.swing.JButton jb_LGLoginButton;
    private javax.swing.JButton jb_ModifyButton;
    private javax.swing.JButton jb_MyProfileButton;
    private javax.swing.JButton jb_PlayButton;
    private javax.swing.JButton jb_RankingButton;
    private javax.swing.JButton jb_ReportsButton;
    private javax.swing.JButton jb_ReportsToMenuButton;
    private javax.swing.JButton jb_SUGoToLoginButton;
    private javax.swing.JButton jb_SUSignUpButton;
    private javax.swing.JButton jb_SettingBackToMenuButton;
    private javax.swing.JButton jb_SettingsButton;
    private javax.swing.JButton jb_SurrenderButton;
    private javax.swing.JButton jb_UpdateButton;
    private javax.swing.JComboBox<String> jcb_DifficultyBox;
    private javax.swing.JComboBox<String> jcb_GamemodebBox;
    private javax.swing.JLabel jl_ChangeNameTitle;
    private javax.swing.JLabel jl_ChangePassTitle;
    private javax.swing.JLabel jl_DifficultyLabel;
    private javax.swing.JLabel jl_EnemyLabel;
    private javax.swing.JLabel jl_EnemyNameGoesHere;
    private javax.swing.JLabel jl_GamemodeLabel;
    private javax.swing.JLabel jl_GhostIcon1;
    private javax.swing.JLabel jl_HisBadGhosts;
    private javax.swing.JLabel jl_HisBadNumber;
    private javax.swing.JLabel jl_HisGoodGhosts;
    private javax.swing.JLabel jl_HisGoodNumber;
    private javax.swing.JLabel jl_LGCreateAccount;
    private javax.swing.JLabel jl_LGLoginMenuTitle;
    private javax.swing.JLabel jl_LGNameLabel;
    private javax.swing.JLabel jl_LGPasswordLabel;
    private javax.swing.JLabel jl_LoggedBadNumber;
    private javax.swing.JLabel jl_LoggedGoodNumber;
    private javax.swing.JLabel jl_LoggedNameGoesHere;
    private javax.swing.JLabel jl_MyProfileTitle;
    private javax.swing.JLabel jl_PasswordGoesHere;
    private javax.swing.JLabel jl_PasswordTitle;
    private javax.swing.JLabel jl_ReportsTitle;
    private javax.swing.JLabel jl_SUGhostIcon;
    private javax.swing.JLabel jl_SUHaveAccount;
    private javax.swing.JLabel jl_SULoginMenuTitle;
    private javax.swing.JLabel jl_SUNameLabel;
    private javax.swing.JLabel jl_SUPasswordLabel;
    private javax.swing.JLabel jl_ScoreGoesHere;
    private javax.swing.JLabel jl_ScoreTitle;
    private javax.swing.JLabel jl_SettingTitle;
    private javax.swing.JLabel jl_UsernameGoesHere;
    private javax.swing.JLabel jl_UsernameTitle;
    private javax.swing.JLabel jl_You;
    private javax.swing.JLabel jl_YourBadGhosts;
    private javax.swing.JLabel jl_board;
    private javax.swing.JPanel jp_10GamesPanel;
    private javax.swing.JPanel jp_BoardPanel;
    private javax.swing.JPanel jp_BoardSidebar;
    private javax.swing.JPanel jp_CardHandler;
    private javax.swing.JPanel jp_LGBackground;
    private javax.swing.JPanel jp_LGDataBackground;
    private javax.swing.JPanel jp_LGToSUPanel;
    private javax.swing.JPanel jp_LIconBackground;
    private javax.swing.JPanel jp_MainMenu;
    private javax.swing.JPanel jp_MenuPanel;
    private javax.swing.JPanel jp_ModifyPanel;
    private javax.swing.JPanel jp_MyProfilePanel;
    private javax.swing.JPanel jp_ProfileDataPanel;
    private javax.swing.JPanel jp_ProfileSettings;
    private javax.swing.JPanel jp_ReportsMenuBG;
    private javax.swing.JPanel jp_ReportsPanel;
    private javax.swing.JPanel jp_SDataBackground;
    private javax.swing.JPanel jp_SUBackground;
    private javax.swing.JPanel jp_SUIconBackground;
    private javax.swing.JPanel jp_SettingsMenuPanel;
    private javax.swing.JPanel jp_SettingsPanel;
    private javax.swing.JPanel jp_ToLogPanel;
    private javax.swing.JSplitPane jsp_GamePanel;
    private javax.swing.JTable jt_10GamesTable;
    private javax.swing.JTextField jtf_LGNameField;
    private javax.swing.JTextField jtf_LGPasswordField;
    private javax.swing.JTextField jtf_NameChangerField;
    private javax.swing.JTextField jtf_PassChangerField;
    private javax.swing.JTextField jtf_SUNameField;
    private javax.swing.JTextField jtf_SUPasswordField;
    // End of variables declaration//GEN-END:variables
    Logger logger = new Logger();
    boolean alreadyInTable = false;
    //ArrayList<Player> Players = new ArrayList<>(); 
}
