
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author smnsl
 */
public class GUI extends javax.swing.JFrame 
{

    /**
     * Creates new form GUI
     */
    public GUI() 
    {
        initComponents();
        jp_MainMenu.setVisible(false);
        jp_MyProfilePanel.setVisible(false);
        jp_ModifyPanel.setVisible(false);
        jp_LGToSUPanel.setVisible(false);
        
        
        
        Player p1 = new Player("Dumy1", "Test1");
        Player p2 = new Player("Dumy2", "Test2");
        logger.addPlayer(p1);
        logger.addPlayer(p2);
        p1.setPlayerScore(123);
        p2.setPlayerScore(123);
        Game[] gr1 = p1.getGameReports();
        for (int i = 0; i < gr1.length; i++)
        {
            gr1[i] = new Game(3, p2.getUsername(), true);
            gr1[i].setDescription("Este es una prueba! Le has ganado a " + p2.getUsername());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_SUBackground = new javax.swing.JPanel();
        jp_SUIconBackground = new javax.swing.JPanel();
        jl_SUGhostIcon = new javax.swing.JLabel();
        jp_SDataBackground = new javax.swing.JPanel();
        jb_SUSignUpButton = new javax.swing.JButton();
        jl_SUNameLabel = new javax.swing.JLabel();
        jl_SULoginMenuTitle = new javax.swing.JLabel();
        jtf_SUNameField = new javax.swing.JTextField();
        jl_SUPasswordLabel = new javax.swing.JLabel();
        jtf_SUPasswordField = new javax.swing.JTextField();
        jp_ToLogPanel = new javax.swing.JPanel();
        jl_SUHaveAccount = new javax.swing.JLabel();
        jb_SUGoToLoginButton = new javax.swing.JButton();
        jp_LGBackground = new javax.swing.JPanel();
        jp_LIconBackground = new javax.swing.JPanel();
        jl_GhostIcon1 = new javax.swing.JLabel();
        jp_LGDataBackground = new javax.swing.JPanel();
        jb_LGLoginButton = new javax.swing.JButton();
        jl_LGNameLabel = new javax.swing.JLabel();
        jl_LGLoginMenuTitle = new javax.swing.JLabel();
        jtf_LGNameField = new javax.swing.JTextField();
        jl_LGPasswordLabel = new javax.swing.JLabel();
        jtf_LGPasswordField = new javax.swing.JTextField();
        jp_LGToSUPanel = new javax.swing.JPanel();
        jl_LGCreateAccount = new javax.swing.JLabel();
        jb_LGGoToSUButton = new javax.swing.JButton();
        jp_MainMenu = new javax.swing.JPanel();
        jp_MenuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jb_PlayButton = new javax.swing.JButton();
        jb_SettingsButton = new javax.swing.JButton();
        jb_ReportsButton = new javax.swing.JButton();
        jb_MyProfileButton = new javax.swing.JButton();
        jb_ExitButton = new javax.swing.JButton();
        jb_CloseSessionButton = new javax.swing.JButton();
        jp_MyProfilePanel = new javax.swing.JPanel();
        jp_ProfileSettings = new javax.swing.JPanel();
        jl_MyProfileTitle = new javax.swing.JLabel();
        jb_BackToMainMenuButton = new javax.swing.JButton();
        jb_ModifyButton = new javax.swing.JButton();
        jb_EraseAccountButton = new javax.swing.JButton();
        jp_ModifyPanel = new javax.swing.JPanel();
        jl_ChangePassTitle = new javax.swing.JLabel();
        jl_ChangeNameTitle = new javax.swing.JLabel();
        jtf_PassChangerField = new javax.swing.JTextField();
        jtf_NameChangerField = new javax.swing.JTextField();
        jb_UpdateButton = new javax.swing.JButton();
        jp_ProfileDataPanel = new javax.swing.JPanel();
        jl_UsernameTitle = new javax.swing.JLabel();
        jl_UsernameGoesHere = new javax.swing.JLabel();
        jl_PasswordTitle = new javax.swing.JLabel();
        jl_PasswordGoesHere = new javax.swing.JLabel();
        jl_ScoreTitle = new javax.swing.JLabel();
        jl_ScoreGoesHere = new javax.swing.JLabel();
        jp_ReportsPanel = new javax.swing.JPanel();
        jp_ReportsMenuBG = new javax.swing.JPanel();
        jl_ReportsTitle = new javax.swing.JLabel();
        jb_RankingButton = new javax.swing.JButton();
        jb_10GamesButton = new javax.swing.JButton();
        jb_ReportsToMenuButton = new javax.swing.JButton();
        jp_10GamesPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_10GamesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ghosts");
        setMinimumSize(new java.awt.Dimension(880, 680));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_SUBackground.setBackground(new java.awt.Color(51, 51, 51));
        jp_SUBackground.setMaximumSize(new java.awt.Dimension(1980, 1080));
        jp_SUBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_SUIconBackground.setBackground(new java.awt.Color(0, 153, 153));
        jp_SUIconBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_SUGhostIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghost.png1.png"))); // NOI18N
        jl_SUGhostIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jp_SUIconBackground.add(jl_SUGhostIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-550, -60, -1, -1));

        jp_SUBackground.add(jp_SUIconBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 680));

        jp_SDataBackground.setBackground(new java.awt.Color(204, 204, 204));
        jp_SDataBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_SUSignUpButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jb_SUSignUpButton.setText("Sign Up");
        jb_SUSignUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_SUSignUpButtonMouseClicked(evt);
            }
        });
        jp_SDataBackground.add(jb_SUSignUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 110, 50));

        jl_SUNameLabel.setBackground(new java.awt.Color(51, 51, 51));
        jl_SUNameLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_SUNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        jl_SUNameLabel.setText("Nombre");
        jp_SDataBackground.add(jl_SUNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jl_SULoginMenuTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jl_SULoginMenuTitle.setForeground(new java.awt.Color(0, 0, 0));
        jl_SULoginMenuTitle.setText("SIGN UP");
        jp_SDataBackground.add(jl_SULoginMenuTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jtf_SUNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_SUNameFieldActionPerformed(evt);
            }
        });
        jp_SDataBackground.add(jtf_SUNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 430, 50));

        jl_SUPasswordLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_SUPasswordLabel.setForeground(new java.awt.Color(51, 51, 51));
        jl_SUPasswordLabel.setText("Contraseña");
        jp_SDataBackground.add(jl_SUPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));
        jp_SDataBackground.add(jtf_SUPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 430, 50));

        jp_ToLogPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_SUHaveAccount.setText("Ya tienes cuenta?");
        jp_ToLogPanel.add(jl_SUHaveAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jb_SUGoToLoginButton.setBackground(new java.awt.Color(204, 204, 204));
        jb_SUGoToLoginButton.setForeground(new java.awt.Color(51, 51, 51));
        jb_SUGoToLoginButton.setText("Log In");
        jb_SUGoToLoginButton.setToolTipText("");
        jb_SUGoToLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_SUGoToLoginButtonMouseClicked(evt);
            }
        });
        jp_ToLogPanel.add(jb_SUGoToLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jp_SDataBackground.add(jp_ToLogPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 200, 40));

        jp_SUBackground.add(jp_SDataBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 550, 680));

        getContentPane().add(jp_SUBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 680));

        jp_LGBackground.setBackground(new java.awt.Color(51, 51, 51));
        jp_LGBackground.setMaximumSize(new java.awt.Dimension(1960, 1080));
        jp_LGBackground.setMinimumSize(new java.awt.Dimension(880, 685));
        jp_LGBackground.setPreferredSize(new java.awt.Dimension(880, 690));
        jp_LGBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_LIconBackground.setBackground(new java.awt.Color(0, 153, 153));
        jp_LIconBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_GhostIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghost.png1.png"))); // NOI18N
        jl_GhostIcon1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jp_LIconBackground.add(jl_GhostIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-550, -60, -1, -1));

        jp_LGBackground.add(jp_LIconBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 680));

        jp_LGDataBackground.setBackground(new java.awt.Color(204, 204, 204));
        jp_LGDataBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_LGLoginButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jb_LGLoginButton.setText("Log In");
        jb_LGLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_LGLoginButtonMouseClicked(evt);
            }
        });
        jp_LGDataBackground.add(jb_LGLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 110, 50));

        jl_LGNameLabel.setBackground(new java.awt.Color(51, 51, 51));
        jl_LGNameLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_LGNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        jl_LGNameLabel.setText("Nombre");
        jp_LGDataBackground.add(jl_LGNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jl_LGLoginMenuTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jl_LGLoginMenuTitle.setForeground(new java.awt.Color(0, 0, 0));
        jl_LGLoginMenuTitle.setText("LOGIN");
        jp_LGDataBackground.add(jl_LGLoginMenuTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));
        jp_LGDataBackground.add(jtf_LGNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 430, 50));

        jl_LGPasswordLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_LGPasswordLabel.setForeground(new java.awt.Color(51, 51, 51));
        jl_LGPasswordLabel.setText("Contraseña");
        jp_LGDataBackground.add(jl_LGPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));
        jp_LGDataBackground.add(jtf_LGPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 430, 50));

        jp_LGToSUPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_LGCreateAccount.setText("No tienes cuenta?");
        jp_LGToSUPanel.add(jl_LGCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jb_LGGoToSUButton.setBackground(new java.awt.Color(204, 204, 204));
        jb_LGGoToSUButton.setForeground(new java.awt.Color(51, 51, 51));
        jb_LGGoToSUButton.setText("Sign Up");
        jb_LGGoToSUButton.setToolTipText("");
        jb_LGGoToSUButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_LGGoToSUButtonMouseClicked(evt);
            }
        });
        jp_LGToSUPanel.add(jb_LGGoToSUButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jp_LGDataBackground.add(jp_LGToSUPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 200, 40));

        jp_LGBackground.add(jp_LGDataBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 550, 680));

        getContentPane().add(jp_LGBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 680));

        jp_MainMenu.setMaximumSize(new java.awt.Dimension(1970, 1080));
        jp_MainMenu.setMinimumSize(new java.awt.Dimension(880, 680));
        jp_MainMenu.setPreferredSize(new java.awt.Dimension(880, 680));
        jp_MainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_MenuPanel.setBackground(new java.awt.Color(102, 102, 102));
        jp_MenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("MAIN MENU");
        jp_MenuPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jb_PlayButton.setText("Play");
        jb_PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_PlayButtonActionPerformed(evt);
            }
        });
        jp_MenuPanel.add(jb_PlayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 120, -1));

        jb_SettingsButton.setText("Settings");
        jp_MenuPanel.add(jb_SettingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 120, -1));

        jb_ReportsButton.setText("Reports");
        jb_ReportsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ReportsButtonMouseClicked(evt);
            }
        });
        jb_ReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ReportsButtonActionPerformed(evt);
            }
        });
        jp_MenuPanel.add(jb_ReportsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 120, -1));

        jb_MyProfileButton.setText("My Profile");
        jb_MyProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_MyProfileButtonMouseClicked(evt);
            }
        });
        jb_MyProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_MyProfileButtonActionPerformed(evt);
            }
        });
        jp_MenuPanel.add(jb_MyProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 120, -1));

        jb_ExitButton.setText("Exit");
        jb_ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ExitButtonMouseClicked(evt);
            }
        });
        jb_ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ExitButtonActionPerformed(evt);
            }
        });
        jp_MenuPanel.add(jb_ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 120, -1));

        jb_CloseSessionButton.setText("Close Session");
        jb_CloseSessionButton.setToolTipText("");
        jb_CloseSessionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CloseSessionButtonMouseClicked(evt);
            }
        });
        jb_CloseSessionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_CloseSessionButtonActionPerformed(evt);
            }
        });
        jp_MenuPanel.add(jb_CloseSessionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 120, -1));

        jp_MainMenu.add(jp_MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 420, 680));

        getContentPane().add(jp_MainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jp_MyProfilePanel.setBackground(new java.awt.Color(204, 204, 204));
        jp_MyProfilePanel.setMaximumSize(new java.awt.Dimension(1970, 1080));
        jp_MyProfilePanel.setMinimumSize(new java.awt.Dimension(880, 512));
        jp_MyProfilePanel.setPreferredSize(new java.awt.Dimension(880, 515));
        jp_MyProfilePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_ProfileSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_MyProfileTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jl_MyProfileTitle.setText("My Profile");
        jp_ProfileSettings.add(jl_MyProfileTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jb_BackToMainMenuButton.setText("Back to menu");
        jb_BackToMainMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_BackToMainMenuButtonMouseClicked(evt);
            }
        });
        jp_ProfileSettings.add(jb_BackToMainMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 130, 50));

        jb_ModifyButton.setText("Modify Profile");
        jb_ModifyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ModifyButtonMouseClicked(evt);
            }
        });
        jb_ModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ModifyButtonActionPerformed(evt);
            }
        });
        jp_ProfileSettings.add(jb_ModifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 130, 50));

        jb_EraseAccountButton.setText("Erase Account");
        jb_EraseAccountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_EraseAccountButtonMouseClicked(evt);
            }
        });
        jp_ProfileSettings.add(jb_EraseAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 130, 50));

        jp_MyProfilePanel.add(jp_ProfileSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 550));

        jp_ModifyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_ChangePassTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_ChangePassTitle.setText("Change your password");
        jp_ModifyPanel.add(jl_ChangePassTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jl_ChangeNameTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_ChangeNameTitle.setText("Change your password");
        jp_ModifyPanel.add(jl_ChangeNameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));
        jp_ModifyPanel.add(jtf_PassChangerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 290, 60));
        jp_ModifyPanel.add(jtf_NameChangerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 290, 60));

        jb_UpdateButton.setText("Update");
        jb_UpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_UpdateButtonMouseClicked(evt);
            }
        });
        jb_UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_UpdateButtonActionPerformed(evt);
            }
        });
        jp_ModifyPanel.add(jb_UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 110, 50));

        jp_MyProfilePanel.add(jp_ModifyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 440, 500));

        jp_ProfileDataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_UsernameTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jl_UsernameTitle.setText("Player Username");
        jp_ProfileDataPanel.add(jl_UsernameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 370, 80));

        jl_UsernameGoesHere.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jp_ProfileDataPanel.add(jl_UsernameGoesHere, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 300, 70));

        jl_PasswordTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jl_PasswordTitle.setText("Password");
        jp_ProfileDataPanel.add(jl_PasswordTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 370, 80));

        jl_PasswordGoesHere.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jp_ProfileDataPanel.add(jl_PasswordGoesHere, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 300, 70));

        jl_ScoreTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jl_ScoreTitle.setText("Total Player Score");
        jp_ProfileDataPanel.add(jl_ScoreTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 370, 80));

        jl_ScoreGoesHere.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jp_ProfileDataPanel.add(jl_ScoreGoesHere, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 300, 70));

        jp_MyProfilePanel.add(jp_ProfileDataPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 440, 500));

        getContentPane().add(jp_MyProfilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 680));

        jp_ReportsPanel.setMaximumSize(new java.awt.Dimension(1970, 1080));
        jp_ReportsPanel.setMinimumSize(new java.awt.Dimension(880, 680));
        jp_ReportsPanel.setPreferredSize(new java.awt.Dimension(880, 685));
        jp_ReportsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_ReportsMenuBG.setBackground(new java.awt.Color(153, 153, 153));
        jp_ReportsMenuBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_ReportsTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jl_ReportsTitle.setForeground(new java.awt.Color(51, 51, 51));
        jl_ReportsTitle.setText("MENU");
        jp_ReportsMenuBG.add(jl_ReportsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jb_RankingButton.setText("Leaderboards");
        jb_RankingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_RankingButtonMouseClicked(evt);
            }
        });
        jp_ReportsMenuBG.add(jb_RankingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 120, 50));

        jb_10GamesButton.setText("Last 10 games");
        jb_10GamesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_10GamesButtonMouseClicked(evt);
            }
        });
        jp_ReportsMenuBG.add(jb_10GamesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 120, 50));

        jb_ReportsToMenuButton.setText("Back to menu");
        jb_ReportsToMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ReportsToMenuButtonMouseClicked(evt);
            }
        });
        jb_ReportsToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ReportsToMenuButtonActionPerformed(evt);
            }
        });
        jp_ReportsMenuBG.add(jb_ReportsToMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 120, 50));

        jp_ReportsPanel.add(jp_ReportsMenuBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 220, 690));

        jp_10GamesPanel.setBackground(new java.awt.Color(102, 102, 102));
        jp_10GamesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jt_10GamesTable.setBackground(new java.awt.Color(153, 153, 153));
        jt_10GamesTable.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jt_10GamesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Game description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_10GamesTable);

        jp_10GamesPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 32, 500, 580));

        jp_ReportsPanel.add(jp_10GamesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 580, 650));

        getContentPane().add(jp_ReportsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 680));

        getAccessibleContext().setAccessibleName("MainFrame");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_LGLoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_LGLoginButtonMouseClicked
        // TODO add your handling code here:
        String nombre = jtf_LGNameField.getText();
        String contra = jtf_LGPasswordField.getText();

        if (nombre.isBlank() || contra.isBlank()) 
        {
            JOptionPane.showMessageDialog(this, "Por favor no dejar casillas vacias.");
        } else 
        {
            if (logger.search(nombre) == null) 
            {
                JOptionPane.showMessageDialog(this, "Este usuario no existe.");
            } else 
            {
                Player p = logger.search(nombre);
                p.setLoggedIn(logger.login(nombre, contra));
                
                if (p.isLoggedIn())
                {
                    
                    JOptionPane.showMessageDialog(this, "Ingresado correctamente.");
                    
                    jp_LGBackground.setVisible(false);
                    jp_MainMenu.setVisible(true);
                    
                }else
                {
                    JOptionPane.showMessageDialog(this, "Contraseña incorrecta.");
                }
                
                logger.listPlayers();
            }
        }
    }//GEN-LAST:event_jb_LGLoginButtonMouseClicked

    private void jtf_SUNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_SUNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_SUNameFieldActionPerformed

    private void jb_SUSignUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_SUSignUpButtonMouseClicked
        // TODO add your handling code here:
        String nombre = jtf_SUNameField.getText();
        String contra = jtf_SUPasswordField.getText();
        
        if (nombre.isBlank() || contra.isBlank() )
        {
            JOptionPane.showMessageDialog(this, "Por favor no dejar casillas vacias.");
        } else
        {
            if ( logger.search(nombre) != null)
            {
                JOptionPane.showMessageDialog(this, "Este usuario ya existe.");
            } else
            {
                Player p = new Player(nombre, contra);
                logger.addPlayer(p);
                p.setLoggedIn(logger.login(nombre, contra));
                JOptionPane.showMessageDialog(this, "Agregado correctamente.");

                
                jp_SUBackground.setVisible(false);
                jp_MainMenu.setVisible(true);
                
                logger.listPlayers();
            }
        }
    }//GEN-LAST:event_jb_SUSignUpButtonMouseClicked

    private void jb_LGGoToSUButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_LGGoToSUButtonMouseClicked
        // TODO add your handling code here:
        jp_LGBackground.setVisible(false);
        jp_SUBackground.setVisible(true);

    }//GEN-LAST:event_jb_LGGoToSUButtonMouseClicked

    private void jb_SUGoToLoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_SUGoToLoginButtonMouseClicked
        // TODO add your handling code here:
        jp_LGBackground.setVisible(true);
        jp_SUBackground.setVisible(false);
        jp_LGToSUPanel.setVisible(true);

    }//GEN-LAST:event_jb_SUGoToLoginButtonMouseClicked

    private void jb_PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_PlayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_PlayButtonActionPerformed

    private void jb_ReportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ReportsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_ReportsButtonActionPerformed

    private void jb_MyProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_MyProfileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_MyProfileButtonActionPerformed

    private void jb_ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ExitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_ExitButtonActionPerformed

    private void jb_ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ExitButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jb_ExitButtonMouseClicked

    private void jb_CloseSessionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CloseSessionButtonMouseClicked
        // TODO add your handling code here:
        
        jp_LGBackground.setVisible(true);
        jp_MainMenu.setVisible(false);
        
        Player p = logger.getLoggedInPlayer();
        p.setLoggedIn(false);
        logger.listPlayers();
        
    }//GEN-LAST:event_jb_CloseSessionButtonMouseClicked

    private void jb_CloseSessionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_CloseSessionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_CloseSessionButtonActionPerformed

    private void jb_ModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ModifyButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jb_ModifyButtonActionPerformed

    private void jb_MyProfileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_MyProfileButtonMouseClicked
        // TODO add your handling code here:
        jp_MainMenu.setVisible(false);
        jp_MyProfilePanel.setVisible(true);
        
        Player p = logger.getLoggedInPlayer();

        jl_UsernameGoesHere.setText(p.getUsername());
        jl_PasswordGoesHere.setText(p.getPassword());
        jl_ScoreGoesHere.setText(p.getPlayerScore() + " points");
        
    }//GEN-LAST:event_jb_MyProfileButtonMouseClicked

    private void jb_ModifyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ModifyButtonMouseClicked
        // TODO add your handling code here:
        Player p = logger.getLoggedInPlayer();
        
        jtf_NameChangerField.setText(p.getUsername());
        jtf_PassChangerField.setText(p.getPassword());
        
        jp_ProfileDataPanel.setVisible(false);
        jp_ModifyPanel.setVisible(true);
        
    }//GEN-LAST:event_jb_ModifyButtonMouseClicked

    private void jb_UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_UpdateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_UpdateButtonActionPerformed

    private void jb_UpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_UpdateButtonMouseClicked
        // TODO add your handling code here:
        Player p = logger.getLoggedInPlayer();
        
        String newName = jtf_NameChangerField.getText();
        String newPass = jtf_PassChangerField.getText();
        
        if (newName.isBlank() || newPass.isBlank())
        {
            JOptionPane.showMessageDialog(this, "No puedes dejar un espacio en blanco.");
        } else
        {
            p.setUsername(newName);
            p.setPassword(newPass);
            JOptionPane.showMessageDialog(this, "Informacion actualizada exitosamente.");
            logger.listPlayers();
            jp_ModifyPanel.setVisible(false);
            jp_ProfileDataPanel.setVisible(true);
            
            
            
            jl_UsernameGoesHere.setText(p.getUsername());
            jl_PasswordGoesHere.setText(p.getPassword());
            jl_ScoreGoesHere.setText(p.getPlayerScore() + " points");
        }
        

        
    }//GEN-LAST:event_jb_UpdateButtonMouseClicked

    private void jb_BackToMainMenuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_BackToMainMenuButtonMouseClicked
        // TODO add your handling code here:
        jp_MyProfilePanel.setVisible(false);
        jp_MainMenu.setVisible(true);
    }//GEN-LAST:event_jb_BackToMainMenuButtonMouseClicked

    private void jb_EraseAccountButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_EraseAccountButtonMouseClicked
        // TODO add your handling code here:
        Player p = logger.getLoggedInPlayer();
        
        logger.getPlayers().remove(p);
        
        jp_LGBackground.setVisible(true);
        //jp_MainMenu.setVisible(false);
        jp_MyProfilePanel.setVisible(false);

        logger.listPlayers();
        
    }//GEN-LAST:event_jb_EraseAccountButtonMouseClicked

    private void jb_10GamesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_10GamesButtonMouseClicked
        // TODO add your handling code here:
        jp_ReportsPanel.setVisible(true);
        jp_10GamesPanel.setVisible(true);
        Player p = logger.getLoggedInPlayer();
        
         //jt_10GamesTable.setModel(new DefaultTableModel(null, new String[]{"Game Description"}));
        
         
        Object rowData[] = new Object[1];
        DefaultTableModel tblm = (DefaultTableModel) jt_10GamesTable.getModel();

        if (!alreadyInTable) 
        {
            for (int i = 0; i < p.getGameReports().length; i++)
            {
                rowData[0] = p.getGameReports()[i].getDescription();

                tblm.addRow(rowData);
                alreadyInTable = true;
            }
        }
            
        
    }//GEN-LAST:event_jb_10GamesButtonMouseClicked

    private void jb_ReportsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ReportsButtonMouseClicked
        // TODO add your handling code here:
        jp_MainMenu.setVisible(false);
        jp_ReportsPanel.setVisible(true);
        jp_10GamesPanel.setVisible(false);
    }//GEN-LAST:event_jb_ReportsButtonMouseClicked

    private void jb_RankingButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_RankingButtonMouseClicked
        // TODO add your handling code here:
        jp_10GamesPanel.setVisible(false);
        jp_ReportsPanel.setVisible(true);
        
        
        
        
        
    }//GEN-LAST:event_jb_RankingButtonMouseClicked

    private void jb_ReportsToMenuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ReportsToMenuButtonMouseClicked
        // TODO add your handling code here:
        jp_MainMenu.setVisible(true);
        jp_ReportsPanel.setVisible(false);
        //jp_ReportsMenuBG.setVisible(false);
        //jp_10GamesPanel.setVisible(false);
        
    }//GEN-LAST:event_jb_ReportsToMenuButtonMouseClicked

    private void jb_ReportsToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ReportsToMenuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_ReportsToMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_10GamesButton;
    private javax.swing.JButton jb_BackToMainMenuButton;
    private javax.swing.JButton jb_CloseSessionButton;
    private javax.swing.JButton jb_EraseAccountButton;
    private javax.swing.JButton jb_ExitButton;
    private javax.swing.JButton jb_LGGoToSUButton;
    private javax.swing.JButton jb_LGLoginButton;
    private javax.swing.JButton jb_ModifyButton;
    private javax.swing.JButton jb_MyProfileButton;
    private javax.swing.JButton jb_PlayButton;
    private javax.swing.JButton jb_RankingButton;
    private javax.swing.JButton jb_ReportsButton;
    private javax.swing.JButton jb_ReportsToMenuButton;
    private javax.swing.JButton jb_SUGoToLoginButton;
    private javax.swing.JButton jb_SUSignUpButton;
    private javax.swing.JButton jb_SettingsButton;
    private javax.swing.JButton jb_UpdateButton;
    private javax.swing.JLabel jl_ChangeNameTitle;
    private javax.swing.JLabel jl_ChangePassTitle;
    private javax.swing.JLabel jl_GhostIcon1;
    private javax.swing.JLabel jl_LGCreateAccount;
    private javax.swing.JLabel jl_LGLoginMenuTitle;
    private javax.swing.JLabel jl_LGNameLabel;
    private javax.swing.JLabel jl_LGPasswordLabel;
    private javax.swing.JLabel jl_MyProfileTitle;
    private javax.swing.JLabel jl_PasswordGoesHere;
    private javax.swing.JLabel jl_PasswordTitle;
    private javax.swing.JLabel jl_ReportsTitle;
    private javax.swing.JLabel jl_SUGhostIcon;
    private javax.swing.JLabel jl_SUHaveAccount;
    private javax.swing.JLabel jl_SULoginMenuTitle;
    private javax.swing.JLabel jl_SUNameLabel;
    private javax.swing.JLabel jl_SUPasswordLabel;
    private javax.swing.JLabel jl_ScoreGoesHere;
    private javax.swing.JLabel jl_ScoreTitle;
    private javax.swing.JLabel jl_UsernameGoesHere;
    private javax.swing.JLabel jl_UsernameTitle;
    private javax.swing.JPanel jp_10GamesPanel;
    private javax.swing.JPanel jp_LGBackground;
    private javax.swing.JPanel jp_LGDataBackground;
    private javax.swing.JPanel jp_LGToSUPanel;
    private javax.swing.JPanel jp_LIconBackground;
    private javax.swing.JPanel jp_MainMenu;
    private javax.swing.JPanel jp_MenuPanel;
    private javax.swing.JPanel jp_ModifyPanel;
    private javax.swing.JPanel jp_MyProfilePanel;
    private javax.swing.JPanel jp_ProfileDataPanel;
    private javax.swing.JPanel jp_ProfileSettings;
    private javax.swing.JPanel jp_ReportsMenuBG;
    private javax.swing.JPanel jp_ReportsPanel;
    private javax.swing.JPanel jp_SDataBackground;
    private javax.swing.JPanel jp_SUBackground;
    private javax.swing.JPanel jp_SUIconBackground;
    private javax.swing.JPanel jp_ToLogPanel;
    private javax.swing.JTable jt_10GamesTable;
    private javax.swing.JTextField jtf_LGNameField;
    private javax.swing.JTextField jtf_LGPasswordField;
    private javax.swing.JTextField jtf_NameChangerField;
    private javax.swing.JTextField jtf_PassChangerField;
    private javax.swing.JTextField jtf_SUNameField;
    private javax.swing.JTextField jtf_SUPasswordField;
    // End of variables declaration//GEN-END:variables
    Logger logger = new Logger();
    boolean alreadyInTable = false;
    //ArrayList<Player> Players = new ArrayList<>(); 
}
